# .readthedocs.yaml

# Required
version: 2

# Set the doc environment.
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

# Build documentation in the doc/sphinx directory.
sphinx:
  configuration: doc/sphinx/source/conf.py

# Declare Python requirements to build the docs.
python:
  install:
  - requirements: doc/sphinx/requirements.txt