name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Python
      run: brew install python@3.9
      
    - name: Install Boost
      run: brew install boost

    - name: Install Boost Python
      run: brew install boost-python3
      
    - name: Install TBB
      run: brew install tbb

    - name: Install OpenImageIO
      run: brew install openimageio
    
    - name: Install OpenEXR
      run: brew install openexr
    
    - name: Install OpenSubdiv
      run: brew install opensubdiv
    
    - name: Install PTex
      run: brew install ptex
    
    - name: Install Alembic
      run: brew install alembic
    
    - name: Install OpenVDB
      run: brew install openvdb
      
    - name: Install Embree
      run: brew install embree
      
    - name: Install PySide6
      run: pip3 install PySide6
      
    - name: Install Jinja2
      run: pip3 install Jinja2

    - name: Configure CMake
      run: cmake -C"${{github.workspace}}/build_files/cmake/config/kraken_release.cmake" -H"${{github.workspace}}" -B"${{github.workspace}}/../build_darwin_release" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: make -s -C ${{github.workspace}}/../build_darwin_release install
      
