name: macOS arm64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      
    - name: Install SVN
      run: brew install svn
      
    - name: Install Python
      run: svn checkout https://svn.blender.org/svnroot/bf-blender/tags/blender-3.2-release/lib/darwin_arm64/python/ ${{github.workspace}}/../lib/apple_darwin_arm64/python/
      
    - name: Install PySide6
      run: ${{github.workspace}}/../lib/apple_darwin_arm64/python/bin/python3.9 -m pip install PySide6
      
    - name: Install PyOpenGL
      run: ${{github.workspace}}/../lib/apple_darwin_arm64/python/bin/python3.9 -m pip install PyOpenGL
      
    - name: Install Jinja2
      run: ${{github.workspace}}/../lib/apple_darwin_arm64/python/bin/python3.9 -m pip install Jinja2
      
    - name: Install Boost
      run: brew install boost

    - name: Install Boost Python
      run: brew install boost-python3
      
    - name: Install TBB
      run: brew install tbb

    - name: Install OpenImageIO
      run: brew install openimageio
    
    - name: Install OpenEXR
      run: brew install openexr
    
    - name: Install OpenSubdiv
      run: brew install opensubdiv
    
    - name: Install PTex
      run: brew install ptex
    
    - name: Install Alembic
      run: brew install alembic
    
    - name: Install OpenVDB
      run: brew install openvdb
      
    - name: Install Embree
      run: brew install embree

    - name: Build
      run: zsh && pwsh && cd ${{github.workspace}} && make release
      
    - name: Package
      run: cd ${{github.workspace}}/../build_darwin_release && cpack -G DragNDrop

    - name: Add Binary
      run: cd ${{github.workspace}}/../build_darwin_release && krakendmgdir=$(find _CPack_Packages -path '*/Darwin/DragNDrop/*-arm64') && rm -r $krakendmgdir/include && rm -r $krakendmgdir/cmake && rm $krakendmgdir/Applications && rm -r $krakendmgdir/Kraken.app/* && cp -R ${{github.workspace}}/../build_darwin_release/bin/Release/Kraken.app/Contents $krakendmgdir/Kraken.app/

    - name: Finalize Package
      run: cd ${{github.workspace}}/../build_darwin_release && krakendmg=$(find . -maxdepth 1 -name '*.dmg') && rm $krakendmg && krakendmgdir=$(find _CPack_Packages -path '*/Darwin/DragNDrop/*-arm64') && create-dmg --app-drop-link 600 250 --volname "Kraken Installer" --volicon "${{github.workspace}}/release/darwin/KrakenInstaller.icns" --window-pos 400 220 --icon "Kraken.app" 140 250 --background ${{github.workspace}}/release/darwin/background.png --window-size 784 520 kraken-1.50a-macos-arm64.dmg $krakendmgdir

    - uses: actions/upload-artifact@v3
      with:
        name: kraken-1.50a-macos-arm64-${{github.sha}}.dmg
        path: ~/actions-runner/_work/Kraken/build_darwin_release/kraken-1.50a-macos-arm64.dmg

    - name: Cleanup
      run: rm ${{github.workspace}}/../build_darwin_release/kraken-1.50a-macos-arm64.dmg