name: macOS arm64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      
    - name: Install SVN
      run: brew install svn
      
    - name: Install Python
      run: svn checkout https://svn.blender.org/svnroot/bf-blender/tags/blender-3.2-release/lib/darwin_arm64/python/ ${{github.workspace}}/../lib/apple_darwin_arm64/python/
      
    - name: Install PySide6
      run: ${{github.workspace}}/../lib/apple_darwin_arm64/python/bin/python3.9 -m pip install PySide6
      
    - name: Install PyOpenGL
      run: ${{github.workspace}}/../lib/apple_darwin_arm64/python/bin/python3.9 -m pip install PyOpenGL
      
    - name: Install Jinja2
      run: ${{github.workspace}}/../lib/apple_darwin_arm64/python/bin/python3.9 -m pip install Jinja2
      
    - name: Install Boost
      run: brew install boost

    - name: Install Boost Python
      run: brew install boost-python3
      
    - name: Install TBB
      run: brew install tbb

    - name: Install OpenImageIO
      run: brew install openimageio
    
    - name: Install OpenEXR
      run: brew install openexr
    
    - name: Install OpenSubdiv
      run: brew install opensubdiv
    
    - name: Install PTex
      run: brew install ptex
    
    - name: Install Alembic
      run: brew install alembic
    
    - name: Install OpenVDB
      run: brew install openvdb
      
    - name: Install Embree
      run: brew install embree
  
    - name: Configure CMake
      run: cmake -C"${{github.workspace}}/build_files/cmake/config/kraken_release.cmake" -H"${{github.workspace}}" -B"${{github.workspace}}/../build_darwin_release" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: make -s -C ${{github.workspace}}/../build_darwin_release install
      
